version: '3'

services:
  reverse-proxy:
    image: my_golang_proxy:latest
    build: 
      context: .
      dockerfile: ./Dockerfile.reverse
    container_name: reverse
    ports:
      - "8080:8080"
        #   environment:
        #      - BACKEND_APP1_NAME=${WEBSERVER1_NAME}
        #      - BACKEND_APP2_NAME=${WEBSERVER2_NAME}
    depends_on:
      - app1
      - app2
    networks:
      - frontend
      - backend

  app1:
    image: webserver-6
    build: 
      context: echo-server
      dockerfile: ./Dockerfile
    container_name: ${WEBSERVER1_NAME}
    hostname: ${WEBSERVER1_NAME}
    environment:
      - EnvPort=8881
      - EnvMessage=hello
    networks:
      - backend

  app2:
    image: webserver-6
    container_name: ${WEBSERVER2_NAME}
    hostname: ${WEBSERVER2_NAME}
    environment:
      - EnvPort=8882
      - EnvMessage=hihi
    networks:
      - backend

networks:
  frontend:
  backend:

