version: '3'

services:
  reverse-proxy:
    image: 0314-reverse-4:latest
    container_name: reverse
    ports:
      - "8080:8080"
    environment:
      - BACKEND_APP1_NAME=${WEBSERVER1_NAME}
      - BACKEND_APP2_NAME=${WEBSERVER2_NAME}
    depends_on:
      - app1
      - app2
    networks:
      - frontend
      - backend

  app1:
    image: 0313-webserver-6
    container_name: ${WEBSERVER1_NAME}
    hostname: ${WEBSERVER1_NAME}
    environment:
      - EnvPort=8881
      - EnvMessage=moi
    networks:
      - backend

  app2:
    image: 0313-webserver-6
    container_name: ${WEBSERVER2_NAME}
    hostname: ${WEBSERVER2_NAME}
    environment:
      - EnvPort=8882
      - EnvMessage=moimoi
    networks:
      - backend

networks:
  frontend:
  backend:

